language: rust

rust:
  - 1.13.0
  - stable
  - beta
  - nightly

cache: cargo

script:
  - cargo build --verbose --features "$FEATURES"
  - cargo test --verbose --features "$FEATURES"

env:
  - FEATURES="hyphenation"
  - FEATURES=""

matrix:
  allow_failures:
    - rust: nightly
