language: rust

rust:
  - stable
  - beta
  - nightly
  - 1.21.0

cache: cargo

env:
  - FEATURES="term_size"
  - FEATURES="hyphenation"

script:
  - cargo build --verbose --features "$FEATURES"
  - cargo test --verbose --features "$FEATURES"

matrix:
  allow_failures:
    - rust: nightly
