language: rust

rust:
  - stable
  - beta
  - nightly
  - 1.23.0

cache: cargo

script:
  - cargo build --verbose --all-features
  - cargo test --verbose --all-features

matrix:
  allow_failures:
    - rust: nightly
