install:
  - ps: Start-FileDownload 'https://static.rust-lang.org/rustup/dist/i686-pc-windows-gnu/rustup-init.exe'
  - rustup-init.exe -y --default-toolchain stable
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin

build_script:
  - cargo build

test_script:
  - cargo test

cache:
  - C:\Users\appveyor\.cargo
  - target
