[package]
name = "textwrap"
version = "0.2.0"
authors = ["Martin Geisler <martin@geisler.net>"]
description = "Library for word wrapping, indenting, and dedenting strings."
documentation = "https://docs.rs/textwrap/"
repository = "https://github.com/mgeisler/textwrap"
readme = "README.md"
keywords = ["text", "formatting", "wrap", "typesetting", "hyphenation"]
license = "MIT"

[dependencies]
unicode-width = "0.1.3"
hyphenation = "0.6.1"
